SUBROUTINE vandermonde(A, B, N)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: A(N, N)
    DOUBLE PRECISION, INTENT(INOUT) :: B(N, 1)
    DOUBLE PRECISION, ALLOCATABLE :: WORK(:)
    INTEGER, INTENT(IN) :: N
    INTEGER :: INFO
    EXTERNAL :: DGELS

    ALLOCATE(WORK(8 * N))
    call DGELS('N', N, N, 1, A, N, B, N, WORK, 8 * N, INFO)
    DEALLOCATE(WORK)
END
