SUBROUTINE vandermonde(A, B, N)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: A(N, N)
    DOUBLE PRECISION, INTENT(INOUT) :: B(N, 1)
    DOUBLE PRECISION :: WORK(8 * N)
    INTEGER, INTENT(IN) :: N
    INTEGER :: INFO
    EXTERNAL :: DGELS

    call DGELS('N', N, N, 1, A, N, B, N, WORK, 8 * N, INFO)
END
